### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by HAJYOUNG** [meaghans/webpage#1]
Hello! I saw your project while I'm searching for a contribution in web design.
I want to contribute in web design and construction. Can you do merge for it?
Have a nice day!

**Comment by meaghans** [comment]
@HAJYOUNG Sure. I have never merged a repository before, so I'm not exactly sure how to do what you're asking. Are you asking me to merge this repository or add you as a collaborator?

**Comment by HAJYOUNG** [comment]
@meaghans Hello! The Merge I mentioned earlier is about whether you can push the repository after I modifying the file! Will it be possible?

**Comment by meaghans** [comment]
@HAJYOUNG Oh, push the repo specifically after you modify my files?

**Comment by HAJYOUNG** [comment]
@meaghans  Yes! Not as a contributor.😊 Just merge on your file.

**Comment by meaghans** [comment]
@HAJYOUNG Yes, I can do that!

**Comment by HAJYOUNG** [comment]
@meaghans  Thanks!😆
